# Generated by Django 3.0.2 on 2020-01-27 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('num_audio_files', models.IntegerField()),
                ('login_date', models.DateTimeField()),
                ('user_type', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=20)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
