# Generated by Django 2.2.7 on 2020-02-11 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('comments', models.TextField(blank=True, default=None, null=True)),
                ('grade', models.CharField(max_length=1)),
                ('submission', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AudioTrim',
            fields=[
                ('audio_trim_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('original_text', models.TextField()),
                ('english_text', models.TextField()),
                ('phonetic_text', models.TextField(blank=True, default=None, null=True)),
                ('last_listened_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('measurements', models.IntegerField(blank=True, default=None, null=True)),
                ('score', models.IntegerField(blank=True, default=None, null=True)),
                ('word_count', models.IntegerField(blank=True, default=None, null=True)),
                ('length', models.IntegerField(blank=True, default=None, null=True)),
                ('start_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BigAudio',
            fields=[
                ('big_audio_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('length', models.TimeField()),
                ('private', models.BooleanField(default=True)),
                ('audio_trims', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='alr.AudioTrim')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('class_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('assignments', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='alr.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('big_audio', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alr.BigAudio')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('lang_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('big_audio', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alr.BigAudio')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('num_audio_files', models.IntegerField(blank=True, default=None, null=True)),
                ('last_login_date', models.DateTimeField(auto_now=True)),
                ('user_type', models.CharField(max_length=15)),
                ('password', models.CharField(default=None, max_length=20)),
                ('firstname', models.CharField(default=None, max_length=20)),
                ('lastname', models.CharField(default=None, max_length=20)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('user_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('assignments', models.ManyToManyField(blank=True, default=None, null=True, to='alr.Assignment')),
                ('audio_trims', models.ManyToManyField(blank=True, default=None, null=True, to='alr.AudioTrim')),
                ('classes', models.ManyToManyField(blank=True, default=None, null=True, to='alr.Class')),
                ('comments', models.ManyToManyField(related_name='big_audio_comments', through='alr.Comment', to='alr.BigAudio')),
                ('languages', models.ManyToManyField(blank=True, default=None, null=True, to='alr.Language')),
                ('reviews', models.ManyToManyField(related_name='big_audio_reviews', through='alr.Review', to='alr.BigAudio')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('speaker_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('languages', models.ManyToManyField(to='alr.Language')),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='alr.User')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alr.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alr.User'),
        ),
        migrations.AddField(
            model_name='class',
            name='language',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alr.Language'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alr.User'),
        ),
        migrations.AddField(
            model_name='bigaudio',
            name='language',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alr.Language'),
        ),
        migrations.AddField(
            model_name='bigaudio',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alr.User'),
        ),
        migrations.AddField(
            model_name='bigaudio',
            name='speaker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alr.Speaker'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='big_audio_files',
            field=models.ManyToManyField(to='alr.BigAudio'),
        ),
    ]
