# Generated by Django 3.0.3 on 2020-03-05 06:48

import alr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigaudio',
            name='sound_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=alr.models.file_directory_path),
        ),
    ]
