# Generated by Django 2.2.7 on 2020-02-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='num_audio_files',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
