# Generated by Django 3.0.2 on 2020-01-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioTrim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('english_text', models.TextField()),
                ('phonetic_text', models.TextField()),
                ('last_listened_date', models.DateTimeField()),
                ('measurements', models.IntegerField()),
                ('score', models.IntegerField()),
                ('word_count', models.IntegerField()),
                ('length', models.IntegerField()),
                ('start_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BigAudio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('upload_date', models.DateField()),
                ('length', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='login_date',
            new_name='last_login_date',
        ),
    ]
