# Generated by Django 2.2.7 on 2020-02-11 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='assignments',
            field=models.ManyToManyField(blank=True, default=None, to='alr.Assignment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='audio_trims',
            field=models.ManyToManyField(blank=True, default=None, to='alr.AudioTrim'),
        ),
        migrations.AlterField(
            model_name='user',
            name='classes',
            field=models.ManyToManyField(blank=True, default=None, to='alr.Class'),
        ),
        migrations.AlterField(
            model_name='user',
            name='languages',
            field=models.ManyToManyField(blank=True, default=None, to='alr.Language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
