# Generated by Django 3.0.2 on 2020-02-12 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('alr', '0002_auto_20200211_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='comments',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='assignment_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='audiotrim',
            old_name='audio_trim_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='bigaudio',
            old_name='big_audio_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='bigaudio',
            old_name='language',
            new_name='language_id',
        ),
        migrations.RenameField(
            model_name='bigaudio',
            old_name='owner',
            new_name='owner_id',
        ),
        migrations.RenameField(
            model_name='bigaudio',
            old_name='speaker',
            new_name='speaker_id',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='class_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='language',
            new_name='language_id',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='teacher',
            new_name='teacher_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='big_audio',
            new_name='big_audio_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='lang_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='big_audio',
            new_name='big_audio_id',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='speaker',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='speaker',
            old_name='speaker_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='speaker',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='speaker',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='bigaudio',
            name='audio_trims',
        ),
        migrations.RemoveField(
            model_name='user',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reviews',
        ),
        migrations.AddField(
            model_name='assignment',
            name='class_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alr.Class'),
        ),
        migrations.AddField(
            model_name='audiotrim',
            name='big_audio_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alr.BigAudio'),
        ),
        migrations.AddField(
            model_name='bigaudio',
            name='comments',
            field=models.ManyToManyField(related_name='big_audio_comments', through='alr.Comment', to='alr.User'),
        ),
        migrations.AddField(
            model_name='bigaudio',
            name='reviews',
            field=models.ManyToManyField(related_name='big_audio_reviews', through='alr.Review', to='alr.User'),
        ),
        migrations.AlterUniqueTogether(
            name='audiotrim',
            unique_together={('big_audio_id', 'start_time')},
        ),
        migrations.RemoveField(
            model_name='audiotrim',
            name='measurements',
        ),
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField(unique=True)),
                ('wavelength', models.IntegerField(blank=True, default=None, null=True)),
                ('frequency', models.IntegerField(blank=True, default=None, null=True)),
                ('audio_trim_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alr.AudioTrim')),
            ],
            options={
                'unique_together': {('audio_trim_id', 'set_number')},
            },
        ),
    ]
