# Generated by Django 3.0.2 on 2020-01-28 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alr', '0002_auto_20200127_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigaudio',
            name='audio_trims',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alr.AudioTrim'),
        ),
        migrations.AddField(
            model_name='bigaudio',
            name='language',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alr.Language'),
        ),
        migrations.AddField(
            model_name='bigaudio',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alr.User'),
        ),
        migrations.AddField(
            model_name='bigaudio',
            name='speaker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alr.Speaker'),
        ),
        migrations.AddField(
            model_name='class',
            name='language',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alr.Language'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alr.User'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='languages',
            field=models.ManyToManyField(to='alr.Language'),
        ),
        migrations.AddField(
            model_name='user',
            name='audio_trims',
            field=models.ManyToManyField(to='alr.AudioTrim'),
        ),
        migrations.AddField(
            model_name='user',
            name='classes',
            field=models.ManyToManyField(to='alr.Class'),
        ),
        migrations.AddField(
            model_name='user',
            name='languages',
            field=models.ManyToManyField(to='alr.Language'),
        ),
        migrations.AddField(
            model_name='user',
            name='speaker',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='alr.Speaker'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('big_audio', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alr.BigAudio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alr.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('big_audio', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alr.BigAudio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alr.User')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('comments', models.TextField()),
                ('grade', models.CharField(max_length=1)),
                ('submission', models.DateTimeField()),
                ('big_audio_files', models.ManyToManyField(to='alr.BigAudio')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='assignments',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alr.Assignment'),
        ),
        migrations.AddField(
            model_name='user',
            name='assignments',
            field=models.ManyToManyField(to='alr.Assignment'),
        ),
        migrations.AddField(
            model_name='user',
            name='comments',
            field=models.ManyToManyField(related_name='big_audio_comments', through='alr.Comment', to='alr.BigAudio'),
        ),
        migrations.AddField(
            model_name='user',
            name='reviews',
            field=models.ManyToManyField(related_name='big_audio_reviews', through='alr.Review', to='alr.BigAudio'),
        ),
    ]
