# Generated by Django 3.0.5 on 2020-04-19 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alr', '0003_auto_20200417_2133'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='audiotrim',
            unique_together=set(),
        ),
    ]
