# Generated by Django 3.0.2 on 2020-02-03 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alr', '0005_auto_20200130_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiotrim',
            name='last_listened_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
